config/routes.rb
Rails.application.routes.draw do
  resources :weathers
  resources :addresses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "weathers#index"
end

app/models/weather.rb
class Weather < ApplicationRecord
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_weather, only: %i[ show edit update destroy ]

  # GET /weathers or /weathers.json
  def index
    @weathers = params[:weathers].blank? ? Weather.all : JSON.parse(params[:weathers]).map { |w| Weather.new(w) }
    @address_str = params[:address]
    @notice = params[:is_cached].to_s.casecmp('true').zero? ? ' (Cached)' : nil
  end

  # GET /weathers/1 or /weathers/1.json
  def show
  end

  # GET /weathers/new
  def new
    @address = Address.new
  end

  # GET /weathers/1/edit
  def edit
  end

  # POST /weathers or /weathers.json
  def create
  end

  # PATCH/PUT /weathers/1 or /weathers/1.json
  def update
    respond_to do |format|
      if @weather.update(weather_params)
        format.html { redirect_to @weather, notice: "Weather was successfully updated." }
        format.json { render :show, status: :ok, location: @weather }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1 or /weathers/1.json
  def destroy
    @weather.destroy!

    respond_to do |format|
      format.html { redirect_to weathers_path, status: :see_other, notice: "Weather was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather
      @weather = Weather.find(params[:id])
    end
end

app/helpers/weathers_helper.rb
module WeathersHelper
  CACHE_EXPIRY = 30.minutes  #Cache the forecast details for 30 minutes for all subsequent requests by zip codes.

  # This is the interface which currently uses 'Open Weather Map' service to gather weather forecast info
  # but we can switch to different services in the future as long as the raw data can be converted to our meta data.
  #
  # Meta Data for weather forecast
  #   [
  #   	{
  #       'time'=> <DateTime>,                  # PST  timezone
  #       'temp'=> <float>,                     # in Fahrenheit
  #       'temp_high'=> <float>,                # in Fahrenheit
  #       'temp_low'=> <float>,                 # in Fahrenheit
  #       'weather_desc'=> <string>,            # such as 'cloudy', 'rain', 'clear sky', etc .....
  #       'weather_OWM_icon_code'=> <string>,   # EX: http://openweathermap.org/img/w/10d.png  for openWeatherMap icon's value = '10d'
  #       'wind'=> <float>,                     # in Mile/Hour
  #       'humidity'=> <integer>                # percentage
  #     },...
  #   ]
  # Return:   <data>, <is_cached_flag>
	def self.get_weather_forecast(address)
    return [OpenWeatherMapHelper.get_weather_forecast(address), false] if address.zip_code.blank?

    # Try to obtain from cache
    data = RedisHelper.get(address.zip_code)
    return [JSON.parse(data), true] if data.present?

    data = OpenWeatherMapHelper.get_weather_forecast(address)
    RedisHelper.set(address.zip_code, data.to_json, CACHE_EXPIRY) if data.present?

    [data, false]
  end

end

app/views/weathers/_form.html.erb
<%= form_with(model: address) do |form| %>
  <div>
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>
  </br>

  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
  </br>

  <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>
  </br>

  <div>
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>
  </br>

  <div>
    <h2> <%= form.submit "Gather Weather Info" %> </h2>
  </div>
<% end %>

app/views/weathers/index.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :title, "Weathers" %>
<head>
</head>
<body>
	<div>
    <h1>Weathers <%= @notice %> </h1>
    <%= link_to "New weather", new_weather_path %>
    <br/><br/>
  </div>
  <div>
    <table id="weatherTable">
    	  <tr>
    	  	<h2><%= @address_str %></h2>
    	  </tr>
        <thead>
            <tr>
                <th>Time (PST)</th>
                <th>Temp (F)</th>
                <th>Temp High (F)</th>
                <th>Temp Low (F)</th>
                <th>Wind (M/H)</th>
                <th>Humidity (%)</th>
                <th>Weather</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @weathers.each do |weather| %>
                <tr>
                	  <td> <%= weather.time.in_time_zone("Pacific Time (US & Canada)").strftime("%A %b %e, %Y at %l:%M %p") %> </td>
                	  <td> <%= weather.temp %> </td>
                	  <td> <%= weather.temp_high %> </td>
                	  <td> <%= weather.temp_low %> </td>
                	  <td> <%= weather.humidity %> </td>
                	  <td> <%= weather.wind %> </td>
                	  <td> <%= weather.weather_desc %> </td>
                	  <td> <img src=<%= "http://openweathermap.org/img/w/#{weather.weather_OWM_icon_code}.png" %> > </td>
                </tr>
            <% end %>
        </tbody>
    </table>
  </div>
</body>

app/views/weathers/new.html.erb
<% content_for :title, "weather" %>

<%= render "form", address: @address, locals: {controller: 'weathers', action: 'create'} %>